# This is a basic workflow to help you get started with Actions

name: FHP-Kursplaner Frontend Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# TODO Implement Data Scraper, and User Authenticator
jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    name: Deploy Frontend
    defaults:
      run:
        working-directory: vue-nuxt
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node.js 10.x
        uses: actions/setup-node@master
        with:
          node-version: 10.x
      - name: Install Dependencies
        run: npm install
      - name: Build Frontend
        run: npm run build
      - name: Deploy Frontend Files
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'fhp_kursplaner_deploy_user'
          server: '116.203.41.131'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './dist/*'
          remote_path: '/static/'
          args: '-o ConnectTimeout=5'
